package com.feng.system.config;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresSchemaTest {

    @Test
    void migrationsDefineAdminAndImageTables() throws Exception {
        String admin = read("db/migration/V1__admin_schema.sql");
        String image = read("db/migration/V2__image_workbench_schema.sql");
        String modelMenus = read("db/data/model_menus.sql");
        String models = read("db/migration/V3__model_configuration.sql");
        String pricing = read("db/migration/V4__model_pricing_and_document_params.sql");
        String fanout = read("db/migration/V5__single_image_request_fanout.sql");
        String video = read("db/migration/V6__video_generation.sql");
        String videoPath = read("db/migration/V7__fix_grok_video_path.sql");

        assertTrue(admin.contains("create table sys_user"));
        assertTrue(admin.contains("generated by default as identity"));
        assertTrue(image.contains("create table api_profiles"));
        assertTrue(image.contains("params jsonb"));
        assertTrue(image.contains("status varchar"));
        assertTrue(modelMenus.contains("模型管理"));
        assertTrue(modelMenus.contains("图片模型"));
        assertTrue(modelMenus.contains("视频模型"));
        assertTrue(modelMenus.contains("模型服务商"));
        assertTrue(modelMenus.contains("sys_role_menu"));
        assertTrue(models.contains("create table model_providers"));
        assertTrue(models.contains("create table ai_models"));
        assertTrue(models.contains("gpt-image-2-1k"));
        assertTrue(models.contains("gpt-image-2-2k"));
        assertTrue(models.contains("gpt-image-2-4k"));
        assertTrue(pricing.contains("unit_price_usd numeric(20,10)"));
        assertTrue(pricing.contains("check (unit_price_usd >= 0)"));
        assertTrue(pricing.contains("gpt-image-2-4k"));
        assertTrue(pricing.contains("'quality'"));
        assertTrue(fanout.contains("set max_count = 10"));
        assertTrue(fanout.contains("model_type = 'image'"));
        assertTrue(video.contains("billing_mode"));
        assertTrue(video.contains("per_request"));
        assertTrue(video.contains("per_second"));
        assertTrue(video.contains("create table video_generation_jobs"));
        assertTrue(video.contains("create table generated_videos"));
        assertTrue(video.contains("seedance-2.0-fast"));
        assertTrue(video.contains("grok-video-1.5"));
        assertTrue(videoPath.contains("generation_path = '/v1/videos'"));
        assertTrue(videoPath.contains("model_key in ('grok-video', 'grok-video-1.5')"));
    }

    @Test
    void omniMigrationSeedsDisabledVideoModelsIdempotently() throws Exception {
        String omni = read("db/migration/V9__omni_video_models.sql");

        assertTrue(omni.contains("https://ai.cangyuansuanli.cn"));
        assertTrue(omni.contains("where not exists (select 1 from restored_provider)"));
        for (String model : new String[]{"omni-fast", "omni-fast-no-water", "omni-v2v", "omni-v2v-no-water"}) {
            assertTrue(omni.contains("('" + model + "'"), model);
        }
        assertTrue(omni.contains("seed.model_key, '/v1/videos'"));
        assertTrue(omni.contains("1, 4, seed.max_images, 0"));
        assertTrue(omni.contains("0, 'per_request', 0, seed.model_sort"));
        assertTrue(omni.contains("\"maximagebytes\":5242880"));
        assertTrue(omni.contains("\"maximagebytes\":8388608"));
        assertTrue(omni.contains("\"maxvideobytes\":8388608"));
        assertTrue(omni.contains("5242880}', 6)"));
        assertTrue(omni.contains("5242880}', 7)"));
        assertTrue(omni.contains("8388608}', 8)"));
        assertTrue(omni.contains("8388608}', 9)"));
        assertTrue(omni.contains("on conflict(model_key) do nothing"));
    }

    @Test
    void omniMigrationReusesAndRestoresCangyuanProvider() throws Exception {
        String omni = read("db/migration/V9__omni_video_models.sql");

        assertTrue(omni.contains("name = '沧元算力'"));
        assertTrue(omni.contains("rtrim(base_url, '/') = 'https://ai.cangyuansuanli.cn'"));
        assertFalse(omni.contains("and deleted = 0"));
        assertTrue(omni.contains("order by case when name = '沧元算力' then 0 else 1 end"));
        assertTrue(omni.contains("update model_providers"));
        assertTrue(omni.contains("set deleted = 0"));
        assertTrue(omni.contains("where id = (select id from existing_provider)"));
        assertTrue(omni.contains("select id from restored_provider union all select id from inserted_provider"));

        String restore = omni.substring(omni.indexOf("update model_providers"), omni.indexOf("returning id", omni.indexOf("update model_providers")));
        assertFalse(restore.contains("api_key"));
        assertFalse(restore.contains("base_url"));
        assertFalse(restore.contains("enabled"));
    }

    @Test
    void databaseCommentsCoverAllTablesAndColumns() throws Exception {
        Map<String, Set<String>> schema = new LinkedHashMap<>();
        for (String migration : List.of(
                "db/migration/V1__admin_schema.sql",
                "db/migration/V2__image_workbench_schema.sql",
                "db/migration/V3__model_configuration.sql",
                "db/migration/V4__model_pricing_and_document_params.sql",
                "db/migration/V6__video_generation.sql",
                "db/migration/V11__generation_request_response_audit.sql")) {
            collectSchema(read(migration), schema);
        }

        String comments = read("db/migration/V13__database_comments.sql");
        for (Map.Entry<String, Set<String>> table : schema.entrySet()) {
            assertTrue(comments.contains("comment on table " + table.getKey() + " is"), table.getKey());
            for (String column : table.getValue()) {
                assertTrue(comments.contains("comment on column " + table.getKey() + "." + column + " is"),
                        table.getKey() + "." + column);
            }
        }
    }

    @Test
    void mediaMigrationsCommentEveryNewTableAndColumn() throws Exception {
        Map<String, Set<String>> schema = new LinkedHashMap<>();
        String models = read("db/migration/V15__media_model_tables.sql");
        String tasks = read("db/migration/V16__media_task_tables.sql");
        collectSchema(models, schema);
        collectSchema(tasks, schema);
        String comments = models + "\n" + tasks;

        for (Map.Entry<String, Set<String>> table : schema.entrySet()) {
            assertTrue(comments.contains("comment on table " + table.getKey() + " is"), table.getKey());
            for (String column : table.getValue()) {
                assertTrue(comments.contains("comment on column " + table.getKey() + "." + column + " is"),
                        table.getKey() + "." + column);
            }
        }
    }

    private void collectSchema(String sql, Map<String, Set<String>> schema) {
        Matcher tableMatcher = Pattern.compile("(?is)create\\s+table\\s+([\\w\"]+)\\s*\\((.*?)\\);").matcher(sql);
        while (tableMatcher.find()) {
            String tableName = normalizeIdentifier(tableMatcher.group(1));
            Set<String> columns = schema.computeIfAbsent(tableName, ignored -> new LinkedHashSet<>());
            for (String definition : splitDefinitions(tableMatcher.group(2))) {
                addColumnFromDefinition(definition, columns);
            }
        }

        Matcher addColumnMatcher = Pattern.compile("(?is)alter\\s+table\\s+([\\w\"]+)\\s+(.*?);").matcher(sql);
        while (addColumnMatcher.find()) {
            String tableName = normalizeIdentifier(addColumnMatcher.group(1));
            Set<String> columns = schema.computeIfAbsent(tableName, ignored -> new LinkedHashSet<>());
            Matcher columnMatcher = Pattern.compile("(?is)add\\s+column\\s+([\\w\"]+)").matcher(addColumnMatcher.group(2));
            while (columnMatcher.find()) {
                columns.add(normalizeIdentifier(columnMatcher.group(1)));
            }
        }
    }

    private void addColumnFromDefinition(String definition, Set<String> columns) {
        String trimmed = definition.strip();
        String lower = trimmed.toLowerCase();
        if (lower.isBlank() || lower.startsWith("constraint ") || lower.startsWith("primary ")
                || lower.startsWith("unique ") || lower.startsWith("foreign ") || lower.startsWith("check ")) {
            return;
        }
        columns.add(normalizeIdentifier(trimmed.split("\\s+", 2)[0]));
    }

    private List<String> splitDefinitions(String body) {
        java.util.ArrayList<String> definitions = new java.util.ArrayList<>();
        StringBuilder current = new StringBuilder();
        int depth = 0;
        for (int i = 0; i < body.length(); i++) {
            char ch = body.charAt(i);
            if (ch == '(') depth++;
            if (ch == ')') depth--;
            if (ch == ',' && depth == 0) {
                definitions.add(current.toString());
                current.setLength(0);
            } else {
                current.append(ch);
            }
        }
        definitions.add(current.toString());
        return definitions;
    }

    private String normalizeIdentifier(String identifier) {
        String normalized = identifier.strip().toLowerCase();
        if (normalized.startsWith("\"") && normalized.endsWith("\"")) {
            return "\"" + normalized.substring(1, normalized.length() - 1) + "\"";
        }
        return normalized;
    }

    private String read(String path) throws Exception {
        ClassPathResource resource = new ClassPathResource(path);
        assertTrue(resource.exists(), path + " must exist");
        return resource.getContentAsString(StandardCharsets.UTF_8).toLowerCase();
    }
}
