package com.feng.system.config;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresSchemaTest {

    @Test
    void migrationsDefineAdminAndImageTables() throws Exception {
        String admin = read("db/migration/V1__admin_schema.sql");
        String image = read("db/migration/V2__image_workbench_schema.sql");
        String modelMenus = read("db/data/model_menus.sql");
        String models = read("db/migration/V3__model_configuration.sql");
        String pricing = read("db/migration/V4__model_pricing_and_document_params.sql");
        String fanout = read("db/migration/V5__single_image_request_fanout.sql");
        String video = read("db/migration/V6__video_generation.sql");
        String videoPath = read("db/migration/V7__fix_grok_video_path.sql");

        assertTrue(admin.contains("create table sys_user"));
        assertTrue(admin.contains("generated by default as identity"));
        assertTrue(image.contains("create table api_profiles"));
        assertTrue(image.contains("params jsonb"));
        assertTrue(image.contains("status varchar"));
        assertTrue(modelMenus.contains("模型管理"));
        assertTrue(modelMenus.contains("图片模型"));
        assertTrue(modelMenus.contains("视频模型"));
        assertTrue(modelMenus.contains("模型服务商"));
        assertTrue(modelMenus.contains("sys_role_menu"));
        assertTrue(models.contains("create table model_providers"));
        assertTrue(models.contains("create table ai_models"));
        assertTrue(models.contains("gpt-image-2-1k"));
        assertTrue(models.contains("gpt-image-2-2k"));
        assertTrue(models.contains("gpt-image-2-4k"));
        assertTrue(pricing.contains("unit_price_usd numeric(20,10)"));
        assertTrue(pricing.contains("check (unit_price_usd >= 0)"));
        assertTrue(pricing.contains("gpt-image-2-4k"));
        assertTrue(pricing.contains("'quality'"));
        assertTrue(fanout.contains("set max_count = 10"));
        assertTrue(fanout.contains("model_type = 'image'"));
        assertTrue(video.contains("billing_mode"));
        assertTrue(video.contains("per_request"));
        assertTrue(video.contains("per_second"));
        assertTrue(video.contains("create table video_generation_jobs"));
        assertTrue(video.contains("create table generated_videos"));
        assertTrue(video.contains("seedance-2.0-fast"));
        assertTrue(video.contains("grok-video-1.5"));
        assertTrue(videoPath.contains("generation_path = '/v1/videos'"));
        assertTrue(videoPath.contains("model_key in ('grok-video', 'grok-video-1.5')"));
    }

    @Test
    void omniMigrationSeedsDisabledVideoModelsIdempotently() throws Exception {
        String omni = read("db/migration/V9__omni_video_models.sql");

        assertTrue(omni.contains("https://ai.cangyuansuanli.cn"));
        assertTrue(omni.contains("where not exists (select 1 from existing_provider)"));
        for (String model : new String[]{"omni-fast", "omni-fast-no-water", "omni-v2v", "omni-v2v-no-water"}) {
            assertTrue(omni.contains("('" + model + "'"), model);
        }
        assertTrue(omni.contains("seed.model_key, '/v1/videos'"));
        assertTrue(omni.contains("1, 4, seed.max_images, 0"));
        assertTrue(omni.contains("0, 'per_request', 0, seed.model_sort"));
        assertTrue(omni.contains("\"maximagebytes\":5242880"));
        assertTrue(omni.contains("\"maximagebytes\":8388608"));
        assertTrue(omni.contains("\"maxvideobytes\":8388608"));
        assertTrue(omni.contains("5242880}', 6)"));
        assertTrue(omni.contains("5242880}', 7)"));
        assertTrue(omni.contains("8388608}', 8)"));
        assertTrue(omni.contains("8388608}', 9)"));
        assertTrue(omni.contains("on conflict(model_key) do nothing"));
    }

    private String read(String path) throws Exception {
        ClassPathResource resource = new ClassPathResource(path);
        assertTrue(resource.exists(), path + " must exist");
        return resource.getContentAsString(StandardCharsets.UTF_8).toLowerCase();
    }
}
