CREATE TABLE media_model_providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    base_url text NOT NULL,
    image_api_key text NOT NULL DEFAULT '',
    video_api_key text NOT NULL DEFAULT '',
    enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    provider_sort integer NOT NULL DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user_id bigint,
    update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1))
);

CREATE TABLE media_ai_models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id bigint NOT NULL REFERENCES media_model_providers(id),
    model_type text NOT NULL CHECK (model_type IN ('IMAGE', 'VIDEO')),
    model_key text NOT NULL UNIQUE,
    display_name text NOT NULL,
    upstream_model text NOT NULL,
    generation_path text NOT NULL,
    edit_path text,
    async_mode smallint NOT NULL DEFAULT 1 CHECK (async_mode IN (0, 1)),
    max_count integer NOT NULL DEFAULT 1 CHECK (max_count BETWEEN 1 AND 10),
    max_reference_images integer NOT NULL DEFAULT 0 CHECK (max_reference_images BETWEEN 0 AND 10),
    supports_mask smallint NOT NULL DEFAULT 0 CHECK (supports_mask IN (0, 1)),
    parameter_schema jsonb NOT NULL DEFAULT '[]'::jsonb,
    default_params jsonb NOT NULL DEFAULT '{}'::jsonb,
    enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    model_sort integer NOT NULL DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user_id bigint,
    update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
    unit_price_usd numeric(20,10) NOT NULL DEFAULT 0.5 CHECK (unit_price_usd >= 0),
    billing_mode varchar(20) NOT NULL DEFAULT 'PER_REQUEST'
        CHECK (billing_mode IN ('PER_REQUEST', 'PER_SECOND'))
);

CREATE INDEX media_ai_models_provider_id_idx ON media_ai_models(provider_id);
CREATE INDEX media_ai_models_type_enabled_idx
    ON media_ai_models(model_type, enabled, model_sort) WHERE deleted = 0;

INSERT INTO media_model_providers (
    id, name, base_url, image_api_key, video_api_key, enabled, provider_sort,
    create_time, update_time, create_user_id, update_user_id, deleted
)
OVERRIDING SYSTEM VALUE
SELECT id, name, base_url, image_api_key, video_api_key, enabled, provider_sort,
       create_time, update_time, create_user_id, update_user_id, deleted
FROM model_providers;

INSERT INTO media_ai_models (
    id, provider_id, model_type, model_key, display_name, upstream_model,
    generation_path, edit_path, async_mode, max_count, max_reference_images,
    supports_mask, parameter_schema, default_params, enabled, model_sort,
    create_time, update_time, create_user_id, update_user_id, deleted,
    unit_price_usd, billing_mode
)
OVERRIDING SYSTEM VALUE
SELECT id, provider_id, model_type, model_key, display_name, upstream_model,
       generation_path, edit_path, async_mode, max_count, max_reference_images,
       supports_mask, parameter_schema, default_params, enabled, model_sort,
       create_time, update_time, create_user_id, update_user_id, deleted,
       unit_price_usd, billing_mode
FROM ai_models;

SELECT setval(
    pg_get_serial_sequence('media_model_providers', 'id'),
    COALESCE((SELECT MAX(id) FROM media_model_providers), 1),
    (SELECT COUNT(*) > 0 FROM media_model_providers)
);

SELECT setval(
    pg_get_serial_sequence('media_ai_models', 'id'),
    COALESCE((SELECT MAX(id) FROM media_ai_models), 1),
    (SELECT COUNT(*) > 0 FROM media_ai_models)
);

DO $$
DECLARE
    source_count bigint;
    target_count bigint;
BEGIN
    SELECT COUNT(*) INTO source_count FROM model_providers;
    SELECT COUNT(*) INTO target_count FROM media_model_providers;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'media_model_providers copy count mismatch: % <> %', source_count, target_count;
    END IF;

    SELECT COUNT(*) INTO source_count FROM ai_models;
    SELECT COUNT(*) INTO target_count FROM media_ai_models;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'media_ai_models copy count mismatch: % <> %', source_count, target_count;
    END IF;

    IF EXISTS (
        SELECT 1 FROM model_providers source
        LEFT JOIN media_model_providers target ON target.id = source.id
        WHERE target.id IS NULL
    ) THEN
        RAISE EXCEPTION 'media_model_providers primary key copy mismatch';
    END IF;

    IF EXISTS (
        SELECT 1 FROM ai_models source
        LEFT JOIN media_ai_models target ON target.id = source.id
        WHERE target.id IS NULL OR target.provider_id <> source.provider_id
    ) THEN
        RAISE EXCEPTION 'media_ai_models primary key or provider copy mismatch';
    END IF;

    IF EXISTS (
        SELECT 1 FROM media_ai_models model
        LEFT JOIN media_model_providers provider ON provider.id = model.provider_id
        WHERE provider.id IS NULL
    ) THEN
        RAISE EXCEPTION 'media_ai_models contains an orphan provider reference';
    END IF;
END $$;

COMMENT ON TABLE media_model_providers IS 'Media model provider configuration';
COMMENT ON TABLE media_ai_models IS 'Media AI model configuration';
COMMENT ON COLUMN media_model_providers.id IS 'Provider ID';
COMMENT ON COLUMN media_model_providers.name IS 'Provider name';
COMMENT ON COLUMN media_model_providers.base_url IS 'Provider base URL';
COMMENT ON COLUMN media_model_providers.image_api_key IS 'Image upstream API key';
COMMENT ON COLUMN media_model_providers.video_api_key IS 'Video upstream API key';
COMMENT ON COLUMN media_model_providers.enabled IS 'Whether the provider is enabled';
COMMENT ON COLUMN media_model_providers.provider_sort IS 'Provider display order';
COMMENT ON COLUMN media_model_providers.create_time IS 'Creation time';
COMMENT ON COLUMN media_model_providers.update_time IS 'Last update time';
COMMENT ON COLUMN media_model_providers.create_user_id IS 'Creator user ID';
COMMENT ON COLUMN media_model_providers.update_user_id IS 'Last updater user ID';
COMMENT ON COLUMN media_model_providers.deleted IS 'Logical deletion flag';
COMMENT ON COLUMN media_ai_models.id IS 'Model ID';
COMMENT ON COLUMN media_ai_models.provider_id IS 'Media provider ID';
COMMENT ON COLUMN media_ai_models.model_type IS 'IMAGE or VIDEO';
COMMENT ON COLUMN media_ai_models.model_key IS 'Public model key';
COMMENT ON COLUMN media_ai_models.display_name IS 'Model display name';
COMMENT ON COLUMN media_ai_models.upstream_model IS 'Model name sent upstream';
COMMENT ON COLUMN media_ai_models.generation_path IS 'Upstream generation API path';
COMMENT ON COLUMN media_ai_models.edit_path IS 'Upstream edit API path';
COMMENT ON COLUMN media_ai_models.async_mode IS 'Whether the model creates asynchronous tasks';
COMMENT ON COLUMN media_ai_models.max_count IS 'Maximum results per request';
COMMENT ON COLUMN media_ai_models.max_reference_images IS 'Maximum reference image count';
COMMENT ON COLUMN media_ai_models.supports_mask IS 'Whether image masks are supported';
COMMENT ON COLUMN media_ai_models.parameter_schema IS 'Public parameter schema';
COMMENT ON COLUMN media_ai_models.default_params IS 'Default generation parameters';
COMMENT ON COLUMN media_ai_models.enabled IS 'Whether the model is enabled';
COMMENT ON COLUMN media_ai_models.model_sort IS 'Model display order';
COMMENT ON COLUMN media_ai_models.create_time IS 'Creation time';
COMMENT ON COLUMN media_ai_models.update_time IS 'Last update time';
COMMENT ON COLUMN media_ai_models.create_user_id IS 'Creator user ID';
COMMENT ON COLUMN media_ai_models.update_user_id IS 'Last updater user ID';
COMMENT ON COLUMN media_ai_models.deleted IS 'Logical deletion flag';
COMMENT ON COLUMN media_ai_models.unit_price_usd IS 'Unit price in USD';
COMMENT ON COLUMN media_ai_models.billing_mode IS 'PER_REQUEST or PER_SECOND';
