CREATE TABLE IF NOT EXISTS gpt_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id varchar(128) NOT NULL,
    user_id varchar(128),
    email varchar(255),
    display_name varchar(255),
    access_token_ciphertext text NOT NULL,
    token_hash char(64) NOT NULL,
    token_expires_at timestamp,
    plan_type varchar(64) NOT NULL DEFAULT 'unknown',
    subscription_plan varchar(128),
    active_subscription boolean NOT NULL DEFAULT false,
    active_subscription_gratis boolean NOT NULL DEFAULT false,
    account_status varchar(32) NOT NULL DEFAULT 'ACTIVE',
    plus_eligibility varchar(32) NOT NULL DEFAULT 'UNKNOWN',
    eligibility_reason varchar(500),
    eligible_offers jsonb NOT NULL DEFAULT '{}'::jsonb,
    eligible_promo_campaigns jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_response jsonb NOT NULL DEFAULT '{}'::jsonb,
    last_checked_at timestamp,
    last_error varchar(500),
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user_id bigint,
    update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS gpt_accounts_account_id_active_uq
    ON gpt_accounts(account_id) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS gpt_accounts_token_hash_active_uq
    ON gpt_accounts(token_hash) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS gpt_accounts_email_idx ON gpt_accounts(email);
CREATE INDEX IF NOT EXISTS gpt_accounts_plan_status_idx
    ON gpt_accounts(plan_type, account_status, plus_eligibility) WHERE deleted = 0;

COMMENT ON TABLE gpt_accounts IS 'Imported ChatGPT accounts and their latest subscription status';
COMMENT ON COLUMN gpt_accounts.id IS 'GPT account record ID';
COMMENT ON COLUMN gpt_accounts.account_id IS 'ChatGPT workspace account ID';
COMMENT ON COLUMN gpt_accounts.user_id IS 'OpenAI user ID extracted from the access token';
COMMENT ON COLUMN gpt_accounts.email IS 'Account email extracted from the access token';
COMMENT ON COLUMN gpt_accounts.display_name IS 'Account display name';
COMMENT ON COLUMN gpt_accounts.access_token_ciphertext IS 'AES-GCM encrypted ChatGPT access token';
COMMENT ON COLUMN gpt_accounts.token_hash IS 'SHA-256 token fingerprint used for deduplication';
COMMENT ON COLUMN gpt_accounts.token_expires_at IS 'Access token expiration time';
COMMENT ON COLUMN gpt_accounts.plan_type IS 'Current plan type reported by ChatGPT';
COMMENT ON COLUMN gpt_accounts.subscription_plan IS 'Current entitlement subscription plan';
COMMENT ON COLUMN gpt_accounts.active_subscription IS 'Whether the account has an active subscription';
COMMENT ON COLUMN gpt_accounts.active_subscription_gratis IS 'Whether the active subscription is gratis';
COMMENT ON COLUMN gpt_accounts.account_status IS 'Latest account availability status';
COMMENT ON COLUMN gpt_accounts.plus_eligibility IS 'Derived free Plus eligibility status';
COMMENT ON COLUMN gpt_accounts.eligibility_reason IS 'Human-readable evidence for the eligibility result';
COMMENT ON COLUMN gpt_accounts.eligible_offers IS 'Eligible offers returned by ChatGPT';
COMMENT ON COLUMN gpt_accounts.eligible_promo_campaigns IS 'Eligible promotional campaigns returned by ChatGPT';
COMMENT ON COLUMN gpt_accounts.raw_response IS 'Latest sanitized account-check response';
COMMENT ON COLUMN gpt_accounts.last_checked_at IS 'Last successful or attempted status refresh time';
COMMENT ON COLUMN gpt_accounts.last_error IS 'Latest safe refresh error without access token content';
COMMENT ON COLUMN gpt_accounts.create_time IS 'Creation time';
COMMENT ON COLUMN gpt_accounts.update_time IS 'Last update time';
COMMENT ON COLUMN gpt_accounts.create_user_id IS 'Creator user ID';
COMMENT ON COLUMN gpt_accounts.update_user_id IS 'Last updater user ID';
COMMENT ON COLUMN gpt_accounts.deleted IS 'Logical deletion flag';

DO $$
DECLARE
    parent_menu_id bigint;
    account_menu_id bigint;
    list_permission_id bigint;
    import_permission_id bigint;
    refresh_permission_id bigint;
    remove_permission_id bigint;
BEGIN
    SELECT id INTO parent_menu_id FROM sys_menu
    WHERE parent_id = 0 AND path = 'gpt-accounts' AND deleted = 0 LIMIT 1;
    IF parent_menu_id IS NULL THEN
        INSERT INTO sys_menu(parent_id, menu_name, menu_type, path, component, permission, icon, menu_sort, visible, create_time, update_time, deleted)
        VALUES (0, 'GPT账号管理', 0, 'gpt-accounts', 'Layout', '', 'UserFilled', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
        RETURNING id INTO parent_menu_id;
    ELSE
        UPDATE sys_menu SET menu_name = 'GPT账号管理', component = 'Layout', icon = 'UserFilled', visible = 1,
            update_time = CURRENT_TIMESTAMP WHERE id = parent_menu_id;
    END IF;

    SELECT id INTO account_menu_id FROM sys_menu
    WHERE parent_id = parent_menu_id AND path = 'gpt-accounts/account' AND deleted = 0 LIMIT 1;
    IF account_menu_id IS NULL THEN
        INSERT INTO sys_menu(parent_id, menu_name, menu_type, path, component, permission, icon, menu_sort, visible, create_time, update_time, deleted)
        VALUES (parent_menu_id, '账号管理', 1, 'gpt-accounts/account', 'views/gpt/GptAccountView.vue', 'gpt:account:list', 'User', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
        RETURNING id INTO account_menu_id;
    ELSE
        UPDATE sys_menu SET menu_name = '账号管理', component = 'views/gpt/GptAccountView.vue',
            permission = 'gpt:account:list', icon = 'User', visible = 1, update_time = CURRENT_TIMESTAMP
        WHERE id = account_menu_id;
    END IF;

    SELECT id INTO list_permission_id FROM sys_menu
    WHERE parent_id = account_menu_id AND permission = 'gpt:account:list' AND menu_type = 2 AND deleted = 0 LIMIT 1;
    IF list_permission_id IS NULL THEN
        INSERT INTO sys_menu(parent_id, menu_name, menu_type, path, component, permission, icon, menu_sort, visible, create_time, update_time, deleted)
        VALUES (account_menu_id, '查询GPT账号', 2, '', '', 'gpt:account:list', '', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
        RETURNING id INTO list_permission_id;
    END IF;

    SELECT id INTO import_permission_id FROM sys_menu
    WHERE parent_id = account_menu_id AND permission = 'gpt:account:import' AND deleted = 0 LIMIT 1;
    IF import_permission_id IS NULL THEN
        INSERT INTO sys_menu(parent_id, menu_name, menu_type, path, component, permission, icon, menu_sort, visible, create_time, update_time, deleted)
        VALUES (account_menu_id, '导入GPT账号', 2, '', '', 'gpt:account:import', '', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
        RETURNING id INTO import_permission_id;
    END IF;

    SELECT id INTO refresh_permission_id FROM sys_menu
    WHERE parent_id = account_menu_id AND permission = 'gpt:account:refresh' AND deleted = 0 LIMIT 1;
    IF refresh_permission_id IS NULL THEN
        INSERT INTO sys_menu(parent_id, menu_name, menu_type, path, component, permission, icon, menu_sort, visible, create_time, update_time, deleted)
        VALUES (account_menu_id, '刷新GPT账号', 2, '', '', 'gpt:account:refresh', '', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
        RETURNING id INTO refresh_permission_id;
    END IF;

    SELECT id INTO remove_permission_id FROM sys_menu
    WHERE parent_id = account_menu_id AND permission = 'gpt:account:remove' AND deleted = 0 LIMIT 1;
    IF remove_permission_id IS NULL THEN
        INSERT INTO sys_menu(parent_id, menu_name, menu_type, path, component, permission, icon, menu_sort, visible, create_time, update_time, deleted)
        VALUES (account_menu_id, '删除GPT账号', 2, '', '', 'gpt:account:remove', '', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
        RETURNING id INTO remove_permission_id;
    END IF;

    INSERT INTO sys_role_menu(role_id, menu_id)
    SELECT id, parent_menu_id FROM sys_role WHERE deleted = 0 ON CONFLICT DO NOTHING;
    INSERT INTO sys_role_menu(role_id, menu_id)
    SELECT id, account_menu_id FROM sys_role WHERE deleted = 0 ON CONFLICT DO NOTHING;
    INSERT INTO sys_role_menu(role_id, menu_id)
    SELECT id, list_permission_id FROM sys_role WHERE deleted = 0 ON CONFLICT DO NOTHING;
    INSERT INTO sys_role_menu(role_id, menu_id)
    SELECT id, import_permission_id FROM sys_role WHERE deleted = 0 ON CONFLICT DO NOTHING;
    INSERT INTO sys_role_menu(role_id, menu_id)
    SELECT id, refresh_permission_id FROM sys_role WHERE deleted = 0 ON CONFLICT DO NOTHING;
    INSERT INTO sys_role_menu(role_id, menu_id)
    SELECT id, remove_permission_id FROM sys_role WHERE deleted = 0 ON CONFLICT DO NOTHING;
END $$;
