CREATE TABLE sys_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key varchar(64) NOT NULL,
    config_name varchar(64) NOT NULL,
    config_value varchar(1000) NOT NULL,
    config_group varchar(32) NOT NULL,
    remark varchar(255), create_time timestamp NOT NULL, update_time timestamp NOT NULL,
    create_user_id bigint, update_user_id bigint, deleted smallint NOT NULL DEFAULT 0,
    CONSTRAINT uk_config_key UNIQUE (config_key)
);

CREATE TABLE sys_dept (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL DEFAULT 0, dept_name varchar(64) NOT NULL, dept_sort integer NOT NULL DEFAULT 0,
    leader varchar(64), phone varchar(32), email varchar(128),
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE TABLE sys_dict_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name varchar(100) NOT NULL, type_code varchar(100) NOT NULL, remark varchar(255),
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0,
    CONSTRAINT uk_dict_type_code_deleted UNIQUE (type_code, deleted)
);

CREATE TABLE sys_dict_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id bigint NOT NULL, dict_label varchar(100) NOT NULL, dict_value varchar(100) NOT NULL,
    dict_sort integer NOT NULL DEFAULT 0, tag_type varchar(32), css_class varchar(100), remark varchar(255),
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0,
    CONSTRAINT uk_dict_type_value_deleted UNIQUE (type_id, dict_value, deleted)
);
CREATE INDEX idx_dict_type_sort ON sys_dict_data(type_id, dict_sort);

CREATE TABLE sys_district (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(20) NOT NULL UNIQUE, name varchar(64) NOT NULL, parent_code varchar(20), level smallint NOT NULL DEFAULT 1,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_district_parent ON sys_district(parent_code);

CREATE TABLE sys_job_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name varchar(64) NOT NULL, task_group varchar(64) NOT NULL DEFAULT 'DEFAULT', cron_expression varchar(128) NOT NULL,
    class_name varchar(255), method_name varchar(128), method_param varchar(1000), handler_key varchar(64), handler_param varchar(1000),
    status smallint NOT NULL DEFAULT 1, remark varchar(255), create_time timestamp NOT NULL, update_time timestamp NOT NULL,
    create_user_id bigint, update_user_id bigint, deleted smallint NOT NULL DEFAULT 0,
    CONSTRAINT uk_task_name_group UNIQUE (task_name, task_group)
);

CREATE TABLE sys_job_task_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL, task_name varchar(64) NOT NULL, task_group varchar(64) NOT NULL,
    class_name varchar(255), method_name varchar(128), method_param varchar(1000), execute_status smallint NOT NULL,
    execute_result varchar(2000), error_message varchar(2000), start_time timestamp NOT NULL, end_time timestamp NOT NULL,
    duration_ms bigint NOT NULL DEFAULT 0, create_time timestamp NOT NULL, update_time timestamp NOT NULL,
    create_user_id bigint, update_user_id bigint, deleted smallint NOT NULL DEFAULT 0
);
CREATE INDEX idx_task_status_time ON sys_job_task_log(task_id, execute_status, create_time);

CREATE TABLE sys_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL DEFAULT 0, menu_name varchar(64) NOT NULL, menu_type smallint NOT NULL,
    path varchar(128), component varchar(128), permission varchar(128), icon varchar(64),
    menu_sort integer NOT NULL DEFAULT 0, visible smallint NOT NULL DEFAULT 1,
    create_time timestamp, update_time timestamp, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE TABLE sys_oper_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_name varchar(128) NOT NULL, business_type varchar(32) NOT NULL, method_name varchar(255), request_uri varchar(255),
    operator_id bigint, operator_name varchar(64), ip_address varchar(64), success smallint NOT NULL DEFAULT 1,
    error_message varchar(500), after_data text, operation_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_api_name_time ON sys_oper_log(api_name, operation_time);
CREATE INDEX idx_operator_time ON sys_oper_log(operator_id, operation_time);

CREATE TABLE sys_post (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_code varchar(64) NOT NULL, post_name varchar(64) NOT NULL, post_sort integer NOT NULL DEFAULT 0, remark varchar(255),
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE TABLE sys_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(64) NOT NULL, role_key varchar(64) NOT NULL UNIQUE, role_sort integer NOT NULL DEFAULT 0, remark varchar(255),
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE TABLE sys_role_menu (role_id bigint NOT NULL, menu_id bigint NOT NULL, PRIMARY KEY(role_id, menu_id));

CREATE TABLE sys_upload_file (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name varchar(255) NOT NULL, current_name varchar(255) NOT NULL, file_size bigint NOT NULL DEFAULT 0,
    file_type varchar(128), md5_value varchar(32) NOT NULL, file_path varchar(500) NOT NULL,
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);
CREATE INDEX idx_md5_value ON sys_upload_file(md5_value);

CREATE TABLE sys_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL UNIQUE, password varchar(255) NOT NULL, nickname varchar(64) NOT NULL,
    phone varchar(32), email varchar(128), dept_id bigint NOT NULL, post_id bigint NOT NULL, status smallint NOT NULL DEFAULT 1,
    create_time timestamp NOT NULL, update_time timestamp NOT NULL, create_user_id bigint, update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0
);

CREATE TABLE sys_user_role (user_id bigint NOT NULL, role_id bigint NOT NULL, PRIMARY KEY(user_id, role_id));
