CREATE TABLE model_providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    base_url text NOT NULL,
    image_api_key text NOT NULL DEFAULT '',
    video_api_key text NOT NULL DEFAULT '',
    enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    provider_sort integer NOT NULL DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user_id bigint,
    update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1))
);

CREATE TABLE ai_models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id bigint NOT NULL REFERENCES model_providers(id),
    model_type text NOT NULL CHECK (model_type IN ('IMAGE', 'VIDEO')),
    model_key text NOT NULL UNIQUE,
    display_name text NOT NULL,
    upstream_model text NOT NULL,
    generation_path text NOT NULL,
    edit_path text,
    async_mode smallint NOT NULL DEFAULT 1 CHECK (async_mode IN (0, 1)),
    max_count integer NOT NULL DEFAULT 1 CHECK (max_count BETWEEN 1 AND 10),
    max_reference_images integer NOT NULL DEFAULT 0 CHECK (max_reference_images BETWEEN 0 AND 10),
    supports_mask smallint NOT NULL DEFAULT 0 CHECK (supports_mask IN (0, 1)),
    parameter_schema jsonb NOT NULL DEFAULT '[]'::jsonb,
    default_params jsonb NOT NULL DEFAULT '{}'::jsonb,
    enabled smallint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    model_sort integer NOT NULL DEFAULT 0,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_user_id bigint,
    update_user_id bigint,
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1))
);
CREATE INDEX ai_models_provider_id_idx ON ai_models(provider_id);
CREATE INDEX ai_models_type_enabled_idx ON ai_models(model_type, enabled, model_sort) WHERE deleted = 0;

ALTER TABLE generation_jobs ADD COLUMN model_config_id bigint REFERENCES ai_models(id);
CREATE INDEX generation_jobs_model_config_id_idx ON generation_jobs(model_config_id);

WITH provider AS (
    INSERT INTO model_providers(name, base_url, image_api_key, video_api_key, enabled, provider_sort)
    VALUES ('沧元算力', 'https://ai.cangyuansuanli.cn', '', '', 1, 1)
    ON CONFLICT(name) DO UPDATE SET base_url = EXCLUDED.base_url, update_time = CURRENT_TIMESTAMP
    RETURNING id
)
INSERT INTO ai_models(provider_id, model_type, model_key, display_name, upstream_model, generation_path,
                      async_mode, max_count, max_reference_images, supports_mask, parameter_schema, default_params, model_sort)
SELECT provider.id, 'IMAGE', model_key, display_name, upstream_model, '/v1/images/generations',
       1, max_count, max_refs, supports_mask, parameter_schema::jsonb, default_params::jsonb, model_sort
FROM provider
CROSS JOIN (VALUES
    ('gpt-image-2', 'GPT Image 2', 'cy-img1-gpt-image-2', 10, 10, 0,
     '[{"key":"size","label":"图片比例","type":"select","default":"1:1","options":[{"label":"自动","value":"auto"},{"label":"1:1","value":"1:1"},{"label":"3:2","value":"3:2"},{"label":"2:3","value":"2:3"}]}]',
     '{"async":true,"stream":false,"response_format":"url"}', 1),
    ('gpt-image-2-1k', 'GPT Image 2 · 1K', 'gpt-image-2-1k', 1, 9, 1,
     '[{"key":"size","label":"尺寸或比例","type":"size","default":"1024x1024","placeholder":"1024x1024 或 16:9","minPixels":655360,"maxPixels":1048576,"maxSide":3840,"multiple":16,"maxRatio":3},{"key":"quality","label":"质量","type":"select","default":"medium","options":[{"label":"自动","value":"auto"},{"label":"低","value":"low"},{"label":"标准","value":"medium"},{"label":"高","value":"high"}]}]',
     '{"async":true,"stream":false,"response_format":"url"}', 2),
    ('gpt-image-2-2k', 'GPT Image 2 · 2K', 'gpt-image-2-2k', 1, 9, 1,
     '[{"key":"size","label":"尺寸或比例","type":"size","default":"2048x2048","placeholder":"2048x2048 或 16:9","minPixels":655360,"maxPixels":4194304,"maxSide":3840,"multiple":16,"maxRatio":3},{"key":"quality","label":"质量","type":"select","default":"medium","options":[{"label":"自动","value":"auto"},{"label":"低","value":"low"},{"label":"标准","value":"medium"},{"label":"高","value":"high"}]}]',
     '{"async":true,"stream":false,"response_format":"url"}', 3),
    ('gpt-image-2-4k', 'GPT Image 2 · 4K', 'gpt-image-2-4k', 1, 9, 1,
     '[{"key":"size","label":"尺寸或比例","type":"size","default":"3840x2160","placeholder":"3840x2160 或 16:9","minPixels":655360,"maxPixels":8294400,"maxSide":3840,"multiple":16,"maxRatio":3},{"key":"quality","label":"质量","type":"select","default":"medium","options":[{"label":"自动","value":"auto"},{"label":"低","value":"low"},{"label":"标准","value":"medium"},{"label":"高","value":"high"}]}]',
     '{"async":true,"stream":false,"response_format":"url"}', 4)
) AS seed(model_key, display_name, upstream_model, max_count, max_refs, supports_mask, parameter_schema, default_params, model_sort)
ON CONFLICT(model_key) DO NOTHING;
